runtime: php55
api_version: 1
threadsafe: true
service: client
skip_files:
- ^node_modules$

handlers:
- url: /
  static_files: build/index.html
  upload: build/index.html

- url: /(.*)
  static_files: build/\1
  upload: build/(.*)
